services:
  # BuffrLend Fintech API Service
  buffrlend-api:
    build: ./backend
    container_name: buffrlend-api
    restart: always
    ports:
      - "8001:8001"
    environment:
      # Environment Configuration
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - NODE_ENV=${NODE_ENV:-development}
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      
      # Authentication Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      
      # Apache Fineract Configuration
      - FINERACT_BASE_URL=${FINERACT_BASE_URL}
      - FINERACT_USERNAME=${FINERACT_USERNAME}
      - FINERACT_PASSWORD=${FINERACT_PASSWORD}
      - FINERACT_TENANT_ID=${FINERACT_TENANT_ID}
      
      # Email Configuration
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-supabase}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_EMAIL=${FROM_EMAIL}
      
      # Payment Gateway Configuration
      - PAYMENT_GATEWAY=${PAYMENT_GATEWAY:-realpay}
      - REALPAY_MERCHANT_ID=${REALPAY_MERCHANT_ID}
      - REALPAY_API_KEY=${REALPAY_API_KEY}
      - REALPAY_WEBHOOK_SECRET=${REALPAY_WEBHOOK_SECRET}
      
      # Adume Integration
      - ADUMO_API_URL=${ADUMO_API_URL}
      - ADUMO_API_KEY=${ADUMO_API_KEY}
      
      # Security Configuration
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:8082}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - buffrlend-network

  # BuffrLend Frontend Service
  buffrlend-frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8001}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        NEXT_PUBLIC_ENVIRONMENT: ${NEXT_PUBLIC_ENVIRONMENT:-development}
    container_name: buffrlend-frontend
    restart: always
    ports:
      - "8082:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8001}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - buffrlend-network
    depends_on:
      - buffrlend-api

  # BuffrLend Worker Service (Background Jobs)
  buffrlend-worker:
    build: ./backend
    container_name: buffrlend-worker
    restart: always
    command: ["npm", "run", "worker"]
    environment:
      # Same environment as API
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FINERACT_BASE_URL=${FINERACT_BASE_URL}
      - FINERACT_USERNAME=${FINERACT_USERNAME}
      - FINERACT_PASSWORD=${FINERACT_PASSWORD}
      - FINERACT_TENANT_ID=${FINERACT_TENANT_ID}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-supabase}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_EMAIL=${FROM_EMAIL}
      - ADUMO_API_URL=${ADUMO_API_URL}
      - ADUMO_API_KEY=${ADUMO_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    networks:
      - buffrlend-network
    depends_on:
      - buffrlend-api

networks:
  buffrlend-network:
    driver: bridge

volumes:
  buffrlend-data: